# Generated by Django 4.2.2 on 2023-06-24 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='human',
            options={'ordering': ['name'], 'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
        migrations.AlterField(
            model_name='human',
            name='age',
            field=models.CharField(max_length=3, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='human',
            name='birthday',
            field=models.CharField(max_length=15, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='human',
            name='height',
            field=models.CharField(max_length=15, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='human',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='human',
            name='surname',
            field=models.CharField(max_length=25, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='human',
            name='weight',
            field=models.CharField(max_length=15, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='human',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Pro.profession', verbose_name='Профессия'),
        ),
    ]
