# Generated by Django 4.2.2 on 2023-06-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pro', '0002_profession_alter_human_options_alter_human_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='human',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={},
        ),
    ]
