# Generated by Django 4.2.2 on 2023-06-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_category_alter_news_options_alter_news_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
    ]
